M48
; DRILL file {KiCad 7.0.6} date Wed Aug  9 00:10:07 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-09T00:10:07+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0295
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.0394
%
G90
G05
T1
X5.7Y-4.5
X5.9Y-4.3
T2
X5.4Y-3.7
X5.4Y-4.0
X5.7Y-3.7
X5.7Y-4.0
X6.0Y-3.7
X6.0Y-4.0
X6.3Y-3.7
X6.3Y-4.0
T3
X5.55Y-4.5
X5.55Y-4.55
X5.55Y-4.6
X6.15Y-4.5
X6.15Y-4.55
X6.15Y-4.6
T4
X5.5Y-4.2
X5.5787Y-4.2
X6.1Y-4.2
X6.1787Y-4.2
T5
X5.4Y-3.4
X5.4Y-3.5
X6.3Y-3.4
X6.3Y-3.5
T6
X5.0Y-4.0
X5.0Y-4.1
T0
M30
